# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yuandong/Dropbox/research/projects/DataDrivenDescent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yuandong/Dropbox/research/projects/DataDrivenDescent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuandong/Dropbox/research/projects/DataDrivenDescent/CMakeFiles /Users/yuandong/Dropbox/research/projects/DataDrivenDescent/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuandong/Dropbox/research/projects/DataDrivenDescent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named deformation_pylib

# Build rule for target.
deformation_pylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deformation_pylib
.PHONY : deformation_pylib

# fast build rule for target.
deformation_pylib/fast:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/build
.PHONY : deformation_pylib/fast

data_driven_descent.pb.o: data_driven_descent.pb.cc.o
.PHONY : data_driven_descent.pb.o

# target to build an object file
data_driven_descent.pb.cc.o:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/data_driven_descent.pb.cc.o
.PHONY : data_driven_descent.pb.cc.o

data_driven_descent.pb.i: data_driven_descent.pb.cc.i
.PHONY : data_driven_descent.pb.i

# target to preprocess a source file
data_driven_descent.pb.cc.i:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/data_driven_descent.pb.cc.i
.PHONY : data_driven_descent.pb.cc.i

data_driven_descent.pb.s: data_driven_descent.pb.cc.s
.PHONY : data_driven_descent.pb.s

# target to generate assembly for a file
data_driven_descent.pb.cc.s:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/data_driven_descent.pb.cc.s
.PHONY : data_driven_descent.pb.cc.s

distortion_py2.o: distortion_py2.cc.o
.PHONY : distortion_py2.o

# target to build an object file
distortion_py2.cc.o:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/distortion_py2.cc.o
.PHONY : distortion_py2.cc.o

distortion_py2.i: distortion_py2.cc.i
.PHONY : distortion_py2.i

# target to preprocess a source file
distortion_py2.cc.i:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/distortion_py2.cc.i
.PHONY : distortion_py2.cc.i

distortion_py2.s: distortion_py2.cc.s
.PHONY : distortion_py2.s

# target to generate assembly for a file
distortion_py2.cc.s:
	$(MAKE) -f CMakeFiles/deformation_pylib.dir/build.make CMakeFiles/deformation_pylib.dir/distortion_py2.cc.s
.PHONY : distortion_py2.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... deformation_pylib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... data_driven_descent.pb.o"
	@echo "... data_driven_descent.pb.i"
	@echo "... data_driven_descent.pb.s"
	@echo "... distortion_py2.o"
	@echo "... distortion_py2.i"
	@echo "... distortion_py2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

